# -*- coding: utf-8 -*-
"""KPDL_B1_BTN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jDoX8QookBgRkPv6T8m6xuegISofA45K

DANH SÁCH THÀNH VIÊN:  
1. Võ Nguyễn Thùy Dương - 2351060006  
2. Phạm Nguyễn Bảo Vi - 2351060041  
3. Phan Tấn Phúc - 2351060029
"""

!pip install openpyxl

import os
os.getcwd()

import pandas as pd

file_path = "20250715-ketquathi-ct2018a.xlsx"   # thay bằng tên file của bạn

all_sheets = pd.read_excel(file_path, sheet_name=["Sheet1", "Sheet2"])

df1 = all_sheets["Sheet1"]
df2 = all_sheets["Sheet2"]

df1.head(), df2.head()

df1_clean = df1.dropna(how="all")
df2_clean = df2.dropna(how="all")

print(len(df1_clean), len(df2_clean))

df_all = pd.concat([df1_clean, df2_clean], ignore_index=True)

print("Sheet1:", len(df1))
print("Sheet2:", len(df2))
print("Tổng sau khi gộp:", len(df_all))

df_all.tail(10)

len(df_all)       # số dòng sau khi gộp
df_all.head()     # xem dữ liệu 5 dòng đầu

df_all = pd.read_excel("20250715-ketquathi-ct2018a.xlsx", dtype={"SOBAODANH": str})

df_all["SOBAODANH"] = df_all["SOBAODANH"].astype(str).str.zfill(8)
df_all["ma_tinh"] = df_all["SOBAODANH"].str[:2]

ma_tinh_map = {
    "01": "Thành phố Hà Nội",
    "02": "Thành phố Hồ Chí Minh",
    "03": "Thành phố Hải Phòng",
    "04": "Thành phố Đà Nẵng",
    "05": "Tỉnh Hà Giang",
    "06": "Tỉnh Cao Bằng",
    "07": "Tỉnh Lai Châu",
    "08": "Tỉnh Lào Cai",
    "09": "Tỉnh Tuyên Quang",
    "10": "Tỉnh Lạng Sơn",
    "11": "Tỉnh Bắc Kạn",
    "12": "Tỉnh Thái Nguyên",
    "13": "Tỉnh Yên Bái",
    "14": "Tỉnh Sơn La",
    "15": "Tỉnh Phú Thọ",
    "16": "Tỉnh Vĩnh Phúc",
    "17": "Tỉnh Quảng Ninh",
    "18": "Tỉnh Bắc Giang",
    "19": "Tỉnh Bắc Ninh",
    "21": "Tỉnh Hải Dương",
    "22": "Tỉnh Hưng Yên",
    "23": "Tỉnh Hòa Bình",
    "24": "Tỉnh Hà Nam",
    "25": "Tỉnh Nam Định",
    "26": "Tỉnh Thái Bình",
    "27": "Tỉnh Ninh Bình",
    "28": "Tỉnh Thanh Hóa",
    "29": "Tỉnh Nghệ An",
    "30": "Tỉnh Hà Tĩnh",
    "31": "Tỉnh Quảng Bình",
    "32": "Tỉnh Quảng Trị",
    "33": "Tỉnh Thừa Thiên - Huế",
    "34": "Tỉnh Quảng Nam",
    "35": "Tỉnh Quảng Ngãi",
    "36": "Tỉnh Kon Tum",
    "37": "Tỉnh Bình Định",
    "38": "Tỉnh Gia Lai",
    "39": "Tỉnh Phú Yên",
    "40": "Tỉnh Đắk Lắk",
    "41": "Tỉnh Khánh Hòa",
    "42": "Tỉnh Lâm Đồng",
    "43": "Tỉnh Bình Phước",
    "44": "Tỉnh Bình Dương",
    "45": "Tỉnh Ninh Thuận",
    "46": "Tỉnh Tây Ninh",
    "47": "Tỉnh Bình Thuận",
    "48": "Tỉnh Đồng Nai",
    "49": "Tỉnh Long An",
    "50": "Tỉnh Đồng Tháp",
    "51": "Tỉnh An Giang",
    "52": "Tỉnh Bà Rịa – Vũng Tàu",
    "53": "Tỉnh Tiền Giang",
    "54": "Tỉnh Kiên Giang",
    "55": "Thành phố Cần Thơ",
    "56": "Tỉnh Bến Tre",
    "57": "Tỉnh Vĩnh Long",
    "58": "Tỉnh Trà Vinh",
    "59": "Tỉnh Sóc Trăng",
    "60": "Tỉnh Bạc Liêu",
    "61": "Tỉnh Cà Mau",
    "62": "Tỉnh Điện Biên",
    "63": "Tỉnh Đăk Nông",
    "64": "Tỉnh Hậu Giang"
}

df_all["ten_tinh"] = df_all["ma_tinh"].map(ma_tinh_map)

df_all[df_all["ten_tinh"].isna()]["ma_tinh"].unique()

df_all[df_all["ma_tinh"] == "00"]["SOBAODANH"].head(20)

subjects = [
    "Toán", "Văn", "Lí", "Hóa", "Sinh",
    "Tin học",
    "Công nghệ công nghiệp",
    "Công nghệ nông nghiệp",
    "Sử", "Địa",
    "Giáo dục kinh tế và pháp luật",
    "Ngoại ngữ"
]

bo_thi = df_all[subjects].isna().sum()
bo_thi

diem_0 = (df_all[subjects] == 0).sum()
diem_0

ty_le_diem_0 = (df_all[subjects] == 0).mean() * 100
ty_le_diem_0

ty_le_bo_thi = df_all[subjects].isna().mean() * 100
ty_le_bo_thi

def central_stats(series):
    series = series.dropna()
    return {
        "mean": series.mean(),
        "median": series.median(),
        "mode": series.mode().iloc[0] if not series.mode().empty else None
    }

stats = {}

for col in subjects:
    stats[col] = central_stats(df_all[col])

df_center = pd.DataFrame(stats).T
df_center

def spread_stats(series):
    s = series.dropna()

    return {
        "min": s.min(),
        "max": s.max(),
        "std": s.std(),       # độ lệch chuẩn
        "var": s.var(),       # phương sai
        "range": s.max() - s.min()
    }

spread = {}

for col in subjects:
    spread[col] = spread_stats(df_all[col])

df_spread = pd.DataFrame(spread).T
df_spread

def score_levels_count(series):
    s = series.dropna()
    total = len(s)

    return {
        "<1":  (s < 1).sum(),
        "<5":  (s < 5).sum(),
        "≥5":  (s >= 5).sum(),
        "≥8":  (s >= 8).sum(),
        "≥9":  (s >= 9).sum(),
        "0 điểm": (s == 0).sum(),
        "Điểm liệt (≤1)": (s <= 1).sum(),
        "Điểm tuyệt đối (10)": (s == 10).sum(),
        "Tổng số thí sinh": total
    }

level_stats = {}

for col in subjects:
    level_stats[col] = score_levels_count(df_all[col])

df_levels = pd.DataFrame(level_stats).T
df_levels

import matplotlib.pyplot as plt

for col in subjects:
    plt.figure(figsize=(8,4))

    stats = score_levels_count(df_all[col])
    labels = list(stats.keys())
    values = list(stats.values())

    plt.barh(labels, values)
    plt.title(f"Tỷ lệ mức điểm môn {col}")
    plt.xlabel("Tỷ lệ (%)")
    plt.tight_layout()
    plt.show()

import matplotlib.pyplot as plt

for col in subjects:
    plt.figure(figsize=(8,4))

    plt.hist(
        df_all[col].dropna(),
        bins=20,
        color="#4DA6FF",         # màu xanh đẹp
        edgecolor="black",       # viền cột
        alpha=0.85               # độ trong suốt
    )

    plt.title(f"Histogram điểm môn {col}", fontsize=13, fontweight="bold")
    plt.xlabel("Điểm", fontsize=11)
    plt.ylabel("Tần suất", fontsize=11)

    plt.grid(axis="y", linestyle="--", alpha=0.5)  # thêm lưới theo trục Y
    plt.tight_layout()
    plt.show()

import matplotlib.pyplot as plt

for col in subjects:
    plt.figure(figsize=(8,4))
    df_all[col].dropna().plot(kind="kde")
    plt.title(f"KDE – phân phối mịn môn {col}")
    plt.xlabel("Điểm")
    plt.tight_layout()
    plt.show()

import matplotlib.pyplot as plt

for col in subjects:
    plt.figure(figsize=(4,6))
    plt.boxplot(df_all[col].dropna(), vert=True)
    plt.title(f"Boxplot môn {col}")
    plt.ylabel("Điểm")
    plt.tight_layout()
    plt.show()

mean_by_province = df_all.groupby("ma_tinh")[subjects].mean().reset_index()

# Nhóm tự nhiên (vàng)
natural_subjects = [
    "Toán", "Lí", "Hóa", "Sinh", "Tin học",
    "Công nghệ công nghiệp", "Công nghệ nông nghiệp"
]

# Nhóm xã hội (hồng)
social_subjects = [
    "Sử", "Địa", "Giáo dục kinh tế và pháp luật"
]

# Ngoại ngữ (xanh)
language_subjects = ["Ngoại ngữ"]

# Ánh xạ
color_map = {}

for sub in natural_subjects:
    color_map[sub] = "#FFD966"   # vàng pastel

for sub in social_subjects:
    color_map[sub] = "#F4B6C2"   # hồng pastel

for sub in language_subjects:
    color_map[sub] = "#A6D1E6"   # xanh pastel

# Thêm màu riêng cho môn Văn (ngôn ngữ)
color_map["Văn"] = "#D9B8FF"     # tím pastel

import matplotlib.pyplot as plt

for col in subjects:
    plt.figure(figsize=(12,6))

    plt.bar(
        mean_by_province["ma_tinh"],
        mean_by_province[col],
        color=color_map[col],
        edgecolor="black"
    )

    plt.title(f"Điểm trung bình môn {col} theo tỉnh", fontsize=13, fontweight="bold")
    plt.xlabel("Mã tỉnh")
    plt.ylabel("Điểm trung bình")
    plt.xticks(rotation=90)

    plt.tight_layout()
    plt.show()

# Khối A00 = Toán + Lí + Hóa
# Khối A01 = Toán + Lí + Ngoại ngữ
# Khối C00 = Văn + Sử + Địa
# Khối D01 = Toán + Văn + Ngoại ngữ

A00 = ["Toán", "Lí", "Hóa"]
A01 = ["Toán", "Lí", "Ngoại ngữ"]
C00 = ["Văn", "Sử", "Địa"]
D01 = ["Toán", "Văn", "Ngoại ngữ"]

df_all["A00"] = df_all[A00].fillna(0).sum(axis=1)
df_all["A01"] = df_all[A01].fillna(0).sum(axis=1)
df_all["C00"] = df_all[C00].fillna(0).sum(axis=1)
df_all["D01"] = df_all[D01].fillna(0).sum(axis=1)

df_all["rank_A00"] = df_all["A00"].rank(ascending=False, method="dense")
df_all["rank_A01"] = df_all["A01"].rank(ascending=False, method="dense")
df_all["rank_C00"] = df_all["C00"].rank(ascending=False, method="dense")
df_all["rank_D01"] = df_all["D01"].rank(ascending=False, method="dense")

df_all.sort_values("A00", ascending=False).head(10)   # Top A00
df_all.sort_values("A01", ascending=False).head(10)   # Top A01
df_all.sort_values("C00", ascending=False).head(10)   # Top C00
df_all.sort_values("D01", ascending=False).head(10)   # Top D01

colors = {
    "A00": "#FF9999",  # đỏ pastel
    "A01": "#FFCC99",  # cam pastel
    "C00": "#99CCFF",  # xanh pastel
    "D01": "#CC99FF",  # tím pastel
}

fig, axes = plt.subplots(2, 2, figsize=(12,8))

khối = ["A00", "A01", "C00", "D01"]

for ax, k in zip(axes.flat, khối):
    ax.hist(df_all[k], bins=20, color=colors[k], edgecolor="black", alpha=0.8)
    ax.set_title(f"Khối {k}", fontsize=12, fontweight="bold")
    ax.set_xlabel("Tổng điểm")
    ax.set_ylabel("Số thí sinh")
    ax.grid(axis="y", linestyle="--", alpha=0.4)

plt.tight_layout()
plt.show()

natural_subjects = ["Toán", "Lí", "Hóa", "Sinh", "Tin học",
                    "Công nghệ công nghiệp", "Công nghệ nông nghiệp"]

social_subjects = ["Văn", "Sử", "Địa", "Giáo dục kinh tế và pháp luật"]

language_subjects = ["Ngoại ngữ"]  # nhóm riêng thiên ngôn ngữ

corr_nat = df_all[natural_subjects].corr(method="pearson")
corr_nat

corr_soc = df_all[social_subjects].corr(method="pearson")
corr_soc

corr_lang = df_all[language_subjects].corr(method="pearson")
corr_lang

plt.figure(figsize=(8,6))
plt.imshow(corr_nat, cmap="coolwarm", vmin=-1, vmax=1)
plt.colorbar(label="Pearson r")
plt.xticks(range(len(natural_subjects)), natural_subjects, rotation=90)
plt.yticks(range(len(natural_subjects)), natural_subjects)
plt.title("Tương quan nhóm Tự nhiên")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,6))
plt.imshow(corr_soc, cmap="coolwarm", vmin=-1, vmax=1)
plt.colorbar(label="Pearson r")
plt.xticks(range(len(social_subjects)), social_subjects, rotation=90)
plt.yticks(range(len(social_subjects)), social_subjects)
plt.title("Tương quan nhóm Xã hội")
plt.tight_layout()
plt.show()